from views.LoginScreen.login_screen import LoginScreen
from views.AboutScreen.about_screen import AboutScreen
from views.PostsScreen.post_screen import PostScreen
from views.InventoryScreen.inventory_screen import InventoryScreen
from views.InventoryDetailScreen.inventory_detail_screen import InventoryDetailScreen